### PR TITLE
Create path if it does not already exist

### PR DESCRIPTION
**Pull request by Quafadas**
Aims to test for the existence of the download directory, and create it should it not already exist.

### CODE REVIEW

**Comment by Quafadas** [comment]
@FantasqueX Apologies to bother - I can see that this fails because of the PS Analyzer task? It looked like an innocuous enough change! 

Unfortunately, I don't understand the error message :-(. Could you offer a hint? And if you're the wrong person to have pinged... my apologies.

**Comment by FantasqueX** [comment]
You can run PSScriptAnalyzer locally. There are some format issues.

**Comment by Quafadas** [comment]
TIL ... that PowerShell runs on MacOS. Thanks for the tip.

**Review by lefou — APPROVED** [review]

**Review by lefou — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
