### PR TITLE
Unify MILL_USER_CACHE_DIR

### PR DESCRIPTION
**Pull request by Flowdalic**

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
Looks good to me. But I now wonder if the `${VAR:-DEFAULT}` expression is supported by all shells?

**Comment by Flowdalic** [comment]
> But I now wonder if the `${VAR:-DEFAULT}` expression is supported by all shells?

It is part of the POSIX sh specification. And most systems have a POSIX (compatible) shell installed and as `sh` in `PATH`, and this is mandated for POSIX compliant systems.

"All shells" is a pretty wide target. But all relevant shells and POSIX'ish shells support it. This include bash and zsh. But not, for example, csh, which is a totally different kind of beast (and probably not installed as `sh` in `PATH`).

**Comment by Flowdalic** [comment]
Furthermore, `shellcheck` automatically selects the POSIX-sh dialect if the she-bang is `sh`. So as long as shellcheck does not complain, your script should be widely portable on all platforms, since POSIX-sh is the least common denominator.

**Comment by lefou** [comment]
Thanks!

**Pull request merged**
